version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
