version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5000
    working_dir: /app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=https://jdakddbhajsrmqelzrwn.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYWtkZGJoYWpzcm1xZWx6cnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzY1MTQsImV4cCI6MjA2Mjk1MjUxNH0.QtkQNusBQjpOsgVsNLOiv8ciuLrGpG2BBdLtRi18Jqo
      - PORT=5000
    working_dir: /app
